### ISSUE TITLE
Add a `TipFile` class for parsing `tips.yml` files

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-core#13]
Add a `TipFile` class for parsing the `tips.yml` file format. The `TipFile` class should provide a `.parse` or `.load` method, and a `random` method which returns a random `Tip` object. The YAML file format will look something like:

```yaml
---
- text: |
    To do blah blah lbah:
    
      ruby_code_here
      
  tags: [tag1, tag2]
- text: ...
  tags: ...
```

Add a `Tip` class which represents an individual tip object (text: `String`, tags: `Array<Sting>`).
